spring:
  application:
    name: backend

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

jwt:
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: ecommerce-api

