spring:
  application:
    name: ecommerce-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true

jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
  issuer: ${JWT_ISSUER:ecommerce-api}

app:
  cookie:
    secure: true

server:
  port: ${SERVER_PORT:8080}