spring:
  config:
    import: optional:file:.env

  application:
    name: backend

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:e-commerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: ecommerce-api

